CATEGORIES = [
    "Shoes",
    "Boots",
    "Trainers",
    "Clothes",
    "Dress",
    "T-shirt",
    "Jeans",
    "Shirts",
    "Printed Shirts",
    "TankTops",
    "Polo Shirt",
    "Beauty",
    "DIY Tools",
    "Garden Outdoors",
    "Grocery",
    "Health Personal Care",
    "Lighting",
]